bag_app/urls.py
""" import modules """
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'), # add_to_bag function in views.py
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'), # adjust_bag function in views.py
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'), # remove_from_bag function in views.py
]

boutique/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # to link up our static and media files
from django.conf.urls.static import static  # to link up our static and media files

from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home_app.urls')),  # tells it to look in the app dir home_app/urls.py
    path('products/', include('products_app.urls')),  # look in the app dir products_app/urls.py
    path('bag/', include('bag_app.urls')),  # look in the app dir products_app/urls.py
    path('checkout/', include('checkout_app.urls')),  # look in the app dir checkout_app/urls.py
    path('profile/', include('profiles_app.urls')),  # look in the app dir profiles_app/urls.py
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'boutique.views.handler404'

products_app/urls.py
# from django.contrib import admin
from django.urls import path
# import views from the current directory
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),

    # django will always use the first URL it finds a matching pattern for.
    # In this case unless we specify that product_id is an integer django 
    # doesn't know the difference between a product number and a string: 
    path('<int:product_id>/', views.product_detail, name='product_detail'), # 'int:' creates it as an integer
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

checkout_app/models.py
""" import models """
import uuid  #used to generate the order no.

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField

from products_app.models import Product
from profiles_app.models import UserProfile

# when a user checks out:
# First use the information they put into the payment form to create an order instance.
# And iterate through the items in the shopping bag.
# Creating an order line item for each one. Attaching it to the order.
# And updating the delivery cost, order total, and grand total.

class Order(models.Model):
    """ Define the variables that allow us to create and track orders """
    
    order_number = models.CharField(max_length=32, null=False, editable=False) # permanent

    # To keep an order history in the admin even if the user is deleted , and
    # able to be null or blank so that users who don't have an account can
    # still make purchases and a related name so we can access the users orders
    # by something like 'user.userprofile.orders':
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL, 
        null=True, blank=True, related_name='orders'
        )
    
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.CharField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True) # not required in every country
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True) # not required in every country
    date = models.DateTimeField(auto_now_add=True) # automatically set date and time on new orders
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID.
        underscore indicates that it is a private method which will only
        be used inside this class.
        """
        return uuid.uuid4().hex.upper()  # to generate a random string of 32 numbers we can use as an Order No.

    def update_total(self):
        """
        Update grand total each time the line item is added,
        accounting for delivery costs
        """
        # the last '0' makes sure that on deletion of all lines, the order total to 'zero' instead of none
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        To override the default save method to create the
        Order No. if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        # execute the original save method
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    """ controls individual shopping bag items in the Order model """
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True) # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        To override the default save method to set the lineitem total 
        and update the order total
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products_app/models.py
from django.db import models

class Category(models.Model):
    """ Category display model for the fixtures in products_app to go in """
    class Meta:
        """ to adjust the verbose name or the plural form from the Django defaults """
        verbose_name_plural = 'Categories'
    
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)  # optional

    def __str__(self):
        """ Takes in category model and returns name """
        return self.name
    
    def get_friendly_name(self):
        """ Takes in category model and returns the friendly_name """
        return self.friendly_name


class Product(models.Model):
    """
    Product display model for the .json fixtures in products_app to go in.
    Foreign key to the category model above, null in DB and blank in forms.
    if a category is deleted, any products that use it will to have null
    for category field rather than deleting the product.
    """
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    # Fields directly from the products.json file
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)  # mimic different sizes for products in the database.
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        """ Takes in product display model and returns name """
        return self.name

products_app/forms.py
""" Import Models """
from django import forms

from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):
    """
    To allow store owners defined as those who are superusers
    in Django the ability to add, update, and delete products in the store.
    """

    class Meta:
        """ Defines the model and fields we wish to include """
        model = Product
        fields = '__all__'

    # Connects to widget in widgets.py to style the admin order list 
    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput) 

    def __init__(self, *args, **kwargs):
        """
        Overrides the __init__ method to make changes to the product form fields.
        """
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()

        # List comprehension for loop to create a list of tuples of the 
        # friendly names associated with their category ids:
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        # To update the category field on the form and use those for choices 
        # instead of using the id:
        self.fields['category'].choices = friendly_names
        
        # iterate through the rest of these fields and set
        # classes on them to match the rest of our store theme:
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products_app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q  # object to generate a search query
from django.db.models.functions import Lower

from .models import Product, Category
from .forms import ProductForm


def all_products(request):
    """ A view to show all products, including sorting and search queries """
    products = Product.objects.all()
    query = None  # ensures no error when loading without a search term
    categories = None  # ensures no error when loading without a categories filter
    sort = None  # ensures no error when loading without a sort filter
    direction = None  # ensures no error when loading without a direction filter

    # To return results where the query was matched in either the product name OR
    # the description. The OR logic is derived through 'Q'.
    # If q is in request.get, set q to equal a variable called 'query'
    # Django messages framework & redirect, reversely back to the products url
    if request.GET:
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))
            
            # Where the name contains the query OR the description contains the query
            # and the i makes the case insensitive
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)
        
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')  # split into a list at the commas
            products = products.filter(category__name__in=categories)  # use list to filter current query to only products whose category 'name' is in the list.
            categories = Category.objects.filter(name__in=categories)  # filter all categories down to the ones whose name is in the list from the URL.
        
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey  # sort into sortkey is to preserve the original field we want it to sort on name.
            
            # Now annotate all the products with a new field:
            if sortkey == 'name':
                sortkey = 'lower_name_annotation'
                products = products.annotate(lower_name_annotation=Lower('name'))
            
            # Categories to be sorted by name instead of their ids
            if sortkey == 'category':
                sortkey = 'category__name'
                # double underscore allows us to drill into a related model, effectively changing
                # products = products.order_by(sortkey) to ...order_by(category__name)

            # To check whether direction is descending
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'descending':  # if direction=descending...
                    sortkey = f'-{sortkey}'  # using string formatting to reverse the order
            
            products = products.order_by(sortkey)  # to sort the products

    # To return the current sorting methodology to the template
    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }
    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """
    product = get_object_or_404(Product, pk=product_id)
    context = {
        'product': product,
    }
    return render(request, 'products/product-detail.html', context)


# @decorators are special functions that wrap around another function
# and return a new one with some additional functionality. Used on the 
# line immediately above the view we wish to decorate:

@login_required
def add_product(request):
    """ Adds a product to the store """

    # To authorize that only superusers to have access to the add, edit, and delete views:
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    # If the request method is post, instantiates a new instance of 
    # the ProductForm and request the image of the product if submitted.
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            # return redirect(reverse('add_product'))

            # instead of redirecting to the add_product page once the product is added
            # instead redirect to that products_detail page like the edit view does:
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()
        
    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)

@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """

    # To authorize that only superusers to have access to the add, edit, and delete views:
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        # prefill form with instance of product obtained above
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')

            # redirect back to the product detail page using the product id:
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure\
                your entries in the form are valid.')
    else:
        # instantiating product form and notifying user of editing capacity:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    # Tell it which template to use and render statement
    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)

@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """

    # To authorize that only superusers to have access to the add, edit, and delete views:
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products_app/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <!-- Header element -->
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>

        <!-- 50% width form to add products to the DB -->
        <div class="row">
            <div class="col-12 col-md-6">
                <!--
                    Encoding type (enctype) attribute needed as potentially be submitting an image file, and without it 
                    the image won't be uploaded properly:
                -->
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <!-- remove the label for the image in product add page -->
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    
                    <!-- Submit and Cancel buttons -->
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

<!-- Js to indicate what the image will be changed to -->
{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        // listen to the change event on the new image input, then 
        // set the filename paragraph in the widget template to the files name
        // with a template literal :
        $('#new-image').change(function() {
            let file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products_app/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <!-- Header element -->
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Edit a Product</h5>
                <hr>
            </div>
        </div>

        <!-- 50% width form to edit products in the DB -->
        <div class="row">
            <div class="col-12 col-md-6">
                <!--
                    Encoding type (enctype) attribute needed as potentially be submitting an image file, and without it 
                    the image won't be uploaded properly. 'edit_product' is in products_app > views.py
                -->
                <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}

                    <!-- remove the label for the image in product edit page -->
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    
                    <!-- Submit and Cancel buttons -->
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Update Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

<!-- Js to indicate what the image will be changed to -->
{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        // listen to the change event on the new image input, then 
        // set the filename paragraph in the widget template to the files name
        // with a template literal :
        $('#new-image').change(function() {
            let file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products_app/templates/products/product-detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <!-- <h1 class="display-4 text-success">Product Page works!</h1> -->
    <div class="overlay"></div>
    <div class="container-fluid">
        
        <!-- product heading  -->
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                
                <!-- Card top with image -->
                <div class="image-container my-5">
                    {% if product.image %}
                        <a href="{{ product.image.url }}" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                        {% else %}
                        <a href="">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            
            <!-- Product details section  -->
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-md-5">
                    
                    <!-- Product Name -->
                    <p class="mb-0">{{ product.name }}</p>
                    
                    <!-- Product Price  -->
                    <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                    {% if product.category %}
                    <p class="small mt-1 mb-0">
                        <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                            <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                        </a>
                    </p>
                    {% endif %}

                    <!-- Rating, if it exists -->
                    {% if product.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}

                    <!-- to add edit and delete links for superusers -->
                    {% if request.user.is_superuser %}
                        <small class="ml-3">
                            <a href="{% url 'edit_product' product.id %}">Edit</a> | 
                            <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                        </small>
                    {% endif %}

                    <!-- Product description -->
                    <p class="mt-3">{{ product.description }}</p>

                    <!-- the form to add the product to the shopping bag that sends information to the server via 'POST' -->
                    <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                        
                        <!-- cross site request forgery token for all forms! -->
                        {% csrf_token %}
                        
                        
                        <div class="form-row">
                            {% with product.has_sizes as s %}
                            {% if s %}
                                <div class="col-12">
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                        <option value="xs">XS</option>
                                        <option value="s">S</option>
                                        <option value="m" selected>M</option>
                                        <option value="l">L</option>
                                        <option value="xl">XL</option>
                                    </select>
                                </div>
                            {% endif %}

                            <!-- Input group containing the quantity input from user allowing quantity and product id to the bag -->
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group input-group-{{ product.id }}">

                                        <!-- Minus 'prepend' button w/ attribute data-item_id -->
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-0 decrement-qty_{{ product.id }}" 
                                                data-item_id="{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        
                                        <!-- Detail view quantity to order field -->
                                        <input class="form-control qty_input id_qty_{{ product.id }}" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ product.id }}">
                                        
                                        <!-- Plus 'append' button w/ attribute data-item_id -->
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-0 increment-qty_{{ product.id }}"
                                                data-item_id="{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Contains the submit and keep shopping buttons for the form -->
                            <div class="col{% if s %}-12 mt-2{% endif %}">

                                <!-- keep shopping button -->
                                <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>

                                <!-- submit button -->
                                <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
                            </div>

                            <!-- To redirect the user back to same page once item is added to the bag -->
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            {% endwith %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!-- To include the postload Js -->
{% block postloadjs %}

<!-- Include the parent block -->
{{ block.super }}

<!-- Include the quantity_input_script.html code -->
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}